language: php

php: [7.1, 7.2]

sudo: required

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  
install:
  - composer install --no-interaction 

script:
 - composer ci

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file: network-rail-schedules.phar
  skip_cleanup: true
  on:
    tags: true
